### ISSUE TITLE
bmctool/utils/seq/auxiliary is accessing Sequence Attribute instead of using get-Methods

### ISSUE THREAD

**Issue by lukas-k** [schuenke/BMCTool#19]
In _bmctool/utils/seq/auxiliary.py_, the following line of code is used (Line 24):
`offsets = seq.definitions['offsets_ppm']`

However, according to pypulseq/Sequence/sequence.py the Sequence-class has no such attribute. The definitions-dictionary or a respective property should rather be accessed using, for example:

`seq.dict_definitions['offsets_ppm']`

or

`seq.get_definition('offsets_ppm')`.

I am using:

- Python 3.9.2
- pypulseq 1.3.1.post1
- BMCTool 0.3.1

Best wishes,
Lukas

**Comment by schuenke** [comment]
Hey @lukas-k,
thanks for bringing this up. The dictionary name changed from _**definitions**_ to **_dict_definitions_** between pypulseq versions 1.2 and 1.3 and I must have forgotten to change it here somehow. I pushed the fix to the dev branch already and will include it in the next release. Until than, you can directly install from the dev branch if you want using:

`pip install git+https://github.com/schuenke/bmctool.git@dev`

At the moment I always access the dictionary directly to ensure getting an error when the definitions entry doesn't exist. However, switching to the get method and catching empty strings as return is probably more elegant and I added it to my to do list. 

Best,
Patrick

**Comment by schuenke** [comment]
hey @lukas-k,
I just released version 0.4.0 where I included the fix. However, I marked the _get_offsets()_ function as deprecated and added a new _get_definition()_ function to the BMCTool instead, that allows to read a single definition directly from a seq file. This is much faster compared to reading the complete seq file (using the pypulseq Sequence.read method) and extracting a single param/value from the dict_definitions dictionary. 

Please let me know if this works for you so I can close this Issue.

**Comment by lukas-k** [comment]
Hello Patrick,
thanks for fixing this issue. The implementation works nicely.
All the best,
Lukas
